import = [
  "/usr/local/lib/node_modules/alacritty-themes/themes/One-Dark.toml"
]

[shell]
program = "/bin/bash"

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 95, lines = 45 }
decorations = "Full"
opacity = 0.9
blur = true
startup_mode = "Windowed"
dynamic_title = true
padding = { x = 5, y = 5 }

[scrolling]
history = 10000
multiplier = 4

[font]
normal.family = "Hack Nerd Font Mono"
bold.family = "Hack Nerd Font Mono"
italic.family = "Hack Nerd Font Mono"
bold_italic.family = "Hack Nerd Font Mono"
size = 13
builtin_box_drawing = true

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = "Block"

[terminal]
osc52 = "CopyPaste"

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
