import = [
  "/usr/local/lib/node_modules/alacritty-themes/themes/vscode.dark.toml"
]

[shell]
program = "/bin/bash"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
blur = true
padding = {x = 10, y = 10}
startup_mode = "Windowed"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 4

[font]
normal.family = "Hack Nerd Font Mono"
size = 14
builtin_box_drawing = true

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
hide_when_typing = true
